### ISSUE TITLE
Peer dependencies handling

### ISSUE THREAD

**Issue by niksy** [niksy/eslint-config-nitpick#49]
https://github.com/eslint/eslint/issues/3458#issuecomment-753534854

**Comment by nkhil** [comment]
Hi @niksy ,

Do you know if installing peer dependencies is still an issue with eslint shared configs? i.e. do you still need to install them all manually?

**Comment by niksy** [comment]
@nkhil that should be handled with npm v7

**Comment by niksy** [comment]
There is no need to reference React or Vue plugins if they won’t be installed if project is not React or Vue based. We only get silly warnings when installing config.

It’s better to document when to install those plugins as opposed to tell users to install them every time.

There are certain plugins that must be installed for base config to work, but all other plugins can be installed when they’re needed.
